# Generated by Django 5.0.2 on 2024-02-27 01:00

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=300)),
                ('imgs', models.FileField(upload_to=shop.models.user_directory_path)),
                ('status', models.CharField(choices=[('availble', 'availble'), ('Finished', 'Finished')], max_length=100)),
                ('category', models.CharField(choices=[('availble', 'availble'), ('Finished', 'Finished')], max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_seller', to='shop.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
