# Generated by Django 5.0.2 on 2024-04-05 11:07

import django.utils.timezone
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_img_product_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgs',
            field=models.FileField(default=django.utils.timezone.now, upload_to=shop.models.user_directory_path),
            preserve_default=False,
        ),
    ]
