# Generated by Django 5.0.2 on 2024-04-05 11:15

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgs',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.get_covert_path),
        ),
    ]
